name = "HypergeoMat"
uuid = "45a664f0-7593-4733-b76c-60f36ef4c15f"
authors = ["Stephane Laurent <adresse@mail.fr>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
